### ISSUE TITLE
Is the Non Local Module trained jointly with other losses? 

### ISSUE THREAD

**Issue by ash1995** [OceanPang/Libra_R-CNN#1]
Hi,

I had a question regarding your use of the non local module for balancing and refining the FPN. Is this module trained along with all the other components of the network?

**Comment by OceanPang** [comment]
@ash1995 The network is trained end-to-end. The non-local module is jointly trained with other modules.

**Comment by OceanPang** [comment]
@ash1995 Yes, there are 4 convolutions added. But we didn't use the pool in your codes. Our code will be released as soon as possible.

**Comment by ash1995** [comment]
Ah ok. The original paper had stated that adding a maxpooling layer after the **phi** and **g** blocks can reduce pairwise computation and increase efficiency. That's why I added it. 

Thank you for clearing my doubts.
