### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by ztt0821** [OceanPang/Libra_R-CNN#11]
Hi,
May I ask do you have a windows version. I can't run compile.sh on windows. I think it needs to do some changes. But I don't know this meaning. Thank you.
if [ -d "build" ]; then
    rm -r build
fi

**Comment by OceanPang** [comment]
The current project doesn't provide Windows version. You may refer to the latest version of mmdetection. But I am afraid of the Windows version wouldn't be supported recently. Pull requests are very welcome!
