### ISSUE TITLE
trian with angle bboxs 

### ISSUE THREAD

**Issue by andrew-begain** [OceanPang/Libra_R-CNN#15]
hi @OceanPang 
I want to train libra-fast- RCNN bboxs with Angle. What should I do?
thank you

**Comment by OceanPang** [comment]
Hi @andrew-begain, sorry for the late reply. Currently, we didn't support training with Angle, you can just add one another regression term along with delta_x, delta_y, delta_w, delta_h. You can refer to some related works in text detection.
