### ISSUE TITLE
The learning rate is related to batch size?

### ISSUE THREAD

**Issue by hdjsjyl** [OceanPang/Libra_R-CNN#5]
Thanks for sharing your work. From ReadMme, I got the learning rate is related to the number of GPUs, so it is also related to the batch size? Thanks

**Comment by OceanPang** [comment]
@hdjsjyl Yes. For example, 2 imgs per gpu with 8 gpus totally on MS COCO needs a lr = 0.02. If you only use 1 gpu. The lr = 0.02 / 8.
