### ISSUE TITLE
Could you show the code position of your work for balancing?

### ISSUE THREAD

**Issue by JoyHuYY1412** [OceanPang/Libra_R-CNN#6]
Could you show the code position of your balancing components in your paper?

**Comment by ShiinaMitsuki** [comment]
I found the **Balanced L1 loss** and **Balanced Feature Pyramid**.
![image](https://user-images.githubusercontent.com/16696202/67265869-602ea780-f4e1-11e9-8baf-914d035dd3dd.png)
